/**
 * Canary English wordlist (en-v1).
 *
 * 2048 words curated for spoken-word clarity. Based on BIP-39 English,
 * filtered for verbal verification: no homophones, no phonetic
 * near-collisions, no emotionally charged words. Backfilled with
 * concrete, unambiguous supplementary words.
 *
 * All words are 3-8 characters, lowercase alphabetic only.
 */

export const WORDLIST: readonly string[] = [
  'ability', 'able', 'about', 'above', 'absent', 'absorb', 'abstract', 'absurd',
  'access', 'accident', 'account', 'accuse', 'achieve', 'acid', 'acorn', 'acoustic',
  'acquire', 'across', 'act', 'action', 'actor', 'actress', 'actual', 'adapt',
  'add', 'addict', 'address', 'adjust', 'admiral', 'admit', 'adult', 'advance',
  'advice', 'aerobic', 'affair', 'afford', 'afraid', 'again', 'age', 'agent',
  'agree', 'ahead', 'aim', 'air', 'airport', 'aisle', 'alarm', 'album',
  'alcohol', 'alert', 'alien', 'all', 'alley', 'allow', 'almost', 'alone',
  'alpha', 'alpine', 'already', 'also', 'always', 'amateur', 'amazing', 'amber',
  'among', 'amount', 'amused', 'analyst', 'anchor', 'ancient', 'anger', 'angle',
  'animal', 'ankle', 'announce', 'annual', 'another', 'answer', 'antenna', 'antique',
  'anvil', 'anxiety', 'any', 'apart', 'apology', 'appear', 'apple', 'approve',
  'april', 'apron', 'arch', 'arctic', 'area', 'arena', 'argue', 'arm',
  'armed', 'armor', 'army', 'around', 'arrange', 'arrive', 'arrow', 'art',
  'artefact', 'artist', 'artwork', 'ask', 'aspect', 'asset', 'assist', 'assume',
  'asthma', 'athlete', 'atom', 'attack', 'attend', 'attitude', 'attract', 'auction',
  'audit', 'august', 'aunt', 'author', 'auto', 'autumn', 'average', 'avocado',
  'avoid', 'awake', 'aware', 'away', 'awesome', 'awful', 'awkward', 'axis',
  'baby', 'bachelor', 'bacon', 'badge', 'badger', 'bag', 'bakery', 'balance',
  'balcony', 'ball', 'balm', 'bamboo', 'banana', 'banjo', 'banner', 'bar',
  'barely', 'bargain', 'barrel', 'base', 'basic', 'basil', 'basket', 'battle',
  'beach', 'beacon', 'bean', 'beauty', 'because', 'become', 'beef', 'beetle',
  'before', 'begin', 'behave', 'behind', 'belfry', 'believe', 'below', 'belt',
  'bench', 'benefit', 'berry', 'best', 'better', 'between', 'beyond', 'bicycle',
  'bid', 'bike', 'bind', 'biology', 'birch', 'bird', 'birth', 'bishop',
  'bitter', 'black', 'blame', 'blanket', 'bleak', 'bless', 'bloom', 'blossom',
  'blouse', 'blue', 'blur', 'blush', 'board', 'boat', 'bobcat', 'body',
  'boil', 'bone', 'bonfire', 'bonus', 'book', 'boost', 'border', 'boring',
  'borrow', 'boss', 'bottom', 'bounce', 'bouquet', 'box', 'boy', 'bracket',
  'brain', 'branch', 'brand', 'brass', 'brave', 'bread', 'breaker', 'breeze',
  'brick', 'bridge', 'brief', 'bright', 'bring', 'brisk', 'broccoli', 'bronze',
  'brook', 'broom', 'brother', 'brown', 'brush', 'bubble', 'buckle', 'buddy',
  'budget', 'buffalo', 'bugle', 'build', 'bulb', 'bulk', 'bumble', 'bundle',
  'bunker', 'burger', 'burrow', 'burst', 'bus', 'bushel', 'business', 'busy',
  'butter', 'buyer', 'buzz', 'cabbage', 'cabin', 'cable', 'cactus', 'cage',
  'cairn', 'cake', 'call', 'calm', 'camel', 'camera', 'camp', 'can',
  'canal', 'cancel', 'candy', 'canoe', 'canopy', 'canvas', 'canyon', 'capable',
  'cape', 'capital', 'captain', 'car', 'caravan', 'carbon', 'card', 'cargo',
  'carpet', 'carry', 'cart', 'case', 'cash', 'casino', 'castle', 'casual',
  'cat', 'catalog', 'catch', 'category', 'cattle', 'caught', 'cause', 'caution',
  'cave', 'cedar', 'ceiling', 'celery', 'cellar', 'cement', 'census', 'century',
  'cereal', 'certain', 'chair', 'chalk', 'champion', 'change', 'chapter', 'charge',
  'charter', 'chase', 'chat', 'cheap', 'check', 'cheese', 'chef', 'cherry',
  'chest', 'chestnut', 'chicken', 'chief', 'child', 'chimney', 'choice', 'choose',
  'chuckle', 'chunk', 'churn', 'cider', 'cigar', 'cinnamon', 'circle', 'citizen',
  'city', 'civil', 'claim', 'clam', 'clap', 'clarify', 'claw', 'clay',
  'clean', 'clerk', 'clever', 'click', 'client', 'cliff', 'climb', 'clinic',
  'clip', 'cloak', 'clock', 'clog', 'close', 'cloth', 'cloud', 'clown',
  'club', 'clump', 'cluster', 'clutch', 'coach', 'coast', 'cobalt', 'cocoa',
  'coconut', 'code', 'codex', 'coffee', 'coil', 'coin', 'collect', 'color',
  'column', 'combine', 'come', 'comet', 'comfort', 'comic', 'common', 'company',
  'concert', 'condor', 'conduct', 'confirm', 'congress', 'connect', 'consider', 'consul',
  'control', 'convince', 'cook', 'cool', 'copper', 'copy', 'coral', 'core',
  'cork', 'corn', 'cornet', 'correct', 'cosmos', 'cost', 'cotton', 'couch',
  'cougar', 'country', 'couple', 'course', 'cousin', 'cover', 'coyote', 'crack',
  'cradle', 'craft', 'cram', 'crane', 'crater', 'crawl', 'cream', 'credit',
  'creek', 'crew', 'cricket', 'crisp', 'critic', 'croft', 'crop', 'cross',
  'crouch', 'crowd', 'crown', 'crucial', 'cruise', 'crumble', 'crunch', 'cry',
  'crystal', 'cube', 'culture', 'cup', 'cupboard', 'curious', 'current', 'curtain',
  'curve', 'cushion', 'custom', 'cute', 'cycle', 'cypress', 'dad', 'dagger',
  'dahlia', 'damp', 'damsel', 'dance', 'danger', 'dapple', 'daring', 'dash',
  'daughter', 'dawn', 'day', 'deal', 'debate', 'decade', 'december', 'decide',
  'decline', 'decorate', 'decrease', 'defense', 'define', 'defy', 'degree', 'delay',
  'deliver', 'delta', 'demand', 'demise', 'denial', 'denim', 'dentist', 'depart',
  'depend', 'deposit', 'depot', 'depth', 'deputy', 'derive', 'describe', 'desert',
  'design', 'desk', 'detail', 'detect', 'develop', 'device', 'devote', 'diagram',
  'dial', 'diamond', 'diary', 'dice', 'diesel', 'diet', 'differ', 'digital',
  'dignity', 'dilemma', 'dinner', 'dinosaur', 'direct', 'dirt', 'disagree', 'discover',
  'dish', 'display', 'distance', 'divert', 'divide', 'divorce', 'dizzy', 'doctor',
  'document', 'dog', 'doll', 'dolphin', 'domain', 'donate', 'donkey', 'donor',
  'door', 'dorsal', 'double', 'dove', 'draft', 'drafter', 'dragon', 'drake',
  'drama', 'drastic', 'draw', 'dream', 'dress', 'drift', 'drifter', 'drill',
  'drink', 'drive', 'drop', 'droplet', 'drum', 'drummer', 'dry', 'duck',
  'dulcet', 'dune', 'dungeon', 'during', 'dusk', 'dust', 'dutch', 'duty',
  'dwarf', 'dynamic', 'eager', 'eagle', 'early', 'earn', 'earth', 'easily',
  'east', 'easy', 'echo', 'ecology', 'economy', 'edge', 'edgeway', 'edit',
  'educate', 'effort', 'egg', 'eight', 'either', 'elbow', 'elder', 'electric',
  'elegant', 'element', 'elephant', 'elevator', 'elite', 'elm', 'else', 'embark',
  'ember', 'embody', 'embrace', 'emerald', 'emerge', 'emotion', 'employ', 'empower',
  'empty', 'enable', 'enact', 'end', 'endless', 'endorse', 'enemy', 'energy',
  'enforce', 'engage', 'engine', 'enhance', 'enjoy', 'enlist', 'enough', 'enrich',
  'enroll', 'ensign', 'ensure', 'enter', 'entire', 'entry', 'envelope', 'episode',
  'epoch', 'equal', 'equip', 'era', 'erase', 'erode', 'erosion', 'error',
  'escape', 'essay', 'essence', 'estate', 'estuary', 'eternal', 'ether', 'ethics',
  'everest', 'evidence', 'evil', 'evolve', 'exact', 'example', 'exchange', 'excite',
  'exclude', 'excuse', 'execute', 'exercise', 'exhaust', 'exhibit', 'exist', 'exit',
  'exotic', 'expand', 'expect', 'explain', 'express', 'extend', 'extra', 'eye',
  'eyebrow', 'fabric', 'face', 'faculty', 'fade', 'faint', 'faith', 'falcon',
  'fall', 'fallow', 'false', 'fame', 'family', 'famous', 'fancy', 'fantasy',
  'farm', 'fashion', 'fat', 'father', 'fathom', 'fatigue', 'favorite', 'feature',
  'february', 'federal', 'fee', 'feed', 'feel', 'female', 'fence', 'fennel',
  'fern', 'festival', 'fetch', 'fever', 'fiber', 'fiction', 'fiddle', 'field',
  'figure', 'file', 'film', 'filter', 'final', 'finch', 'find', 'finger',
  'finish', 'fire', 'firm', 'first', 'fiscal', 'fish', 'fit', 'fitness',
  'fix', 'fjord', 'flag', 'flagon', 'flame', 'flannel', 'flash', 'flat',
  'flavor', 'flicker', 'flight', 'flint', 'flip', 'float', 'flock', 'floor',
  'floret', 'fluid', 'flush', 'flutter', 'fly', 'foal', 'foam', 'focus',
  'fog', 'foil', 'fold', 'follow', 'food', 'foot', 'force', 'forest',
  'forge', 'forget', 'fork', 'fortune', 'forum', 'forward', 'fossil', 'foster',
  'found', 'foundry', 'fox', 'foxglove', 'fragile', 'frame', 'frequent', 'fresco',
  'fresh', 'friend', 'fringe', 'frog', 'front', 'frost', 'frown', 'frozen',
  'fruit', 'fuel', 'fun', 'funny', 'furnace', 'furrow', 'future', 'gadget',
  'gain', 'galaxy', 'gallery', 'galley', 'game', 'gap', 'garage', 'garbage',
  'garden', 'garland', 'garlic', 'garment', 'garnet', 'gas', 'gasp', 'gate',
  'gather', 'gauge', 'gaze', 'gazelle', 'general', 'genius', 'genre', 'gentle',
  'genuine', 'gesture', 'geyser', 'giant', 'gibbon', 'gift', 'giggle', 'ginger',
  'giraffe', 'girl', 'give', 'glacier', 'glad', 'glance', 'glare', 'glass',
  'glen', 'glide', 'glimpse', 'globe', 'gloom', 'glory', 'glove', 'glow',
  'glue', 'goat', 'goblet', 'goddess', 'gold', 'golden', 'good', 'goose',
  'gopher', 'gorge', 'gorilla', 'gospel', 'gossip', 'govern', 'gown', 'grab',
  'grace', 'grain', 'granite', 'grant', 'grape', 'grass', 'gravity', 'great',
  'green', 'grid', 'grocery', 'group', 'grow', 'grunt', 'guard', 'guess',
  'guide', 'guilt', 'guitar', 'guppy', 'gust', 'gym', 'habit', 'half',
  'hamlet', 'hammer', 'hammock', 'hamster', 'hand', 'happy', 'harbor', 'hard',
  'harness', 'harvest', 'hat', 'have', 'hawk', 'hawthorn', 'head', 'health',
  'heart', 'hearth', 'heavy', 'hedgehog', 'height', 'hello', 'helmet', 'help',
  'hen', 'herald', 'hermit', 'hero', 'heron', 'hickory', 'hidden', 'high',
  'hill', 'hint', 'hip', 'hire', 'history', 'hobby', 'hockey', 'hold',
  'hole', 'holiday', 'hollow', 'home', 'homeward', 'honey', 'hood', 'hope',
  'horizon', 'horn', 'hornet', 'horse', 'hospital', 'host', 'hotel', 'hour',
  'hover', 'howler', 'hub', 'huge', 'human', 'humble', 'humor', 'hundred',
  'hungry', 'hunt', 'hunter', 'hurdle', 'hurry', 'husband', 'hybrid', 'ice',
  'icon', 'idea', 'identify', 'idle', 'igloo', 'ignore', 'ill', 'image',
  'imitate', 'immune', 'impact', 'improve', 'inch', 'include', 'income', 'increase',
  'index', 'indicate', 'indigo', 'indoor', 'industry', 'infant', 'inflict', 'inform',
  'inhale', 'inherit', 'initial', 'inject', 'inkwell', 'inlet', 'inmate', 'inner',
  'innocent', 'input', 'inquiry', 'insect', 'inside', 'inspire', 'install', 'intact',
  'interest', 'into', 'invest', 'invite', 'involve', 'inward', 'iris', 'iron',
  'island', 'issue', 'item', 'ivory', 'jacket', 'jade', 'jaguar', 'jar',
  'jasmine', 'javelin', 'jazz', 'jeans', 'jelly', 'jersey', 'jewel', 'job',
  'join', 'joke', 'jostle', 'journal', 'journey', 'joy', 'jubilee', 'judge',
  'juice', 'jumble', 'jump', 'junco', 'jungle', 'junior', 'juniper', 'just',
  'kangaroo', 'kayak', 'keen', 'keep', 'keeper', 'kelp', 'kennel', 'kernel',
  'kestrel', 'ketchup', 'kettle', 'key', 'kick', 'kid', 'kidney', 'kind',
  'kindle', 'kingdom', 'kinglet', 'kipper', 'kiss', 'kit', 'kitchen', 'kite',
  'kitten', 'kiwi', 'knapsack', 'knee', 'knife', 'knock', 'lab', 'label',
  'labor', 'ladder', 'lady', 'lake', 'lamp', 'language', 'lantern', 'lapis',
  'laptop', 'larch', 'large', 'later', 'latin', 'laugh', 'laundry', 'laurel',
  'lava', 'lavender', 'law', 'lawn', 'layer', 'lazy', 'leader', 'leaf',
  'learn', 'leave', 'lecture', 'left', 'leg', 'legal', 'legend', 'leisure',
  'lemon', 'lend', 'length', 'lens', 'leopard', 'lesson', 'letter', 'level',
  'liar', 'liberty', 'library', 'license', 'lichen', 'life', 'lift', 'light',
  'like', 'limit', 'linden', 'link', 'linnet', 'lion', 'liquid', 'list',
  'little', 'live', 'lizard', 'llama', 'load', 'loan', 'lobster', 'local',
  'lock', 'locust', 'lodge', 'logic', 'long', 'loom', 'loop', 'lottery',
  'lotus', 'loud', 'lounge', 'love', 'loyal', 'lucky', 'luggage', 'lumber',
  'lumen', 'lunar', 'lunch', 'luxury', 'machine', 'mackerel', 'magic', 'magnet',
  'main', 'major', 'make', 'mammal', 'man', 'manage', 'mandate', 'mango',
  'mansion', 'mantis', 'manual', 'maple', 'marble', 'march', 'margin', 'marine',
  'market', 'marriage', 'marsh', 'marten', 'mask', 'masonry', 'mass', 'master',
  'match', 'material', 'math', 'matrix', 'matter', 'maximum', 'maze', 'meadow',
  'mean', 'measure', 'mechanic', 'medal', 'media', 'melody', 'melt', 'member',
  'memory', 'mention', 'menu', 'mercy', 'merge', 'merit', 'merlin', 'merry',
  'mesa', 'mesh', 'message', 'metal', 'method', 'micron', 'middle', 'midnight',
  'milk', 'millet', 'million', 'mimic', 'mind', 'minimum', 'minnow', 'minor',
  'minute', 'miracle', 'mirage', 'mirror', 'miss', 'mistake', 'mix', 'mixed',
  'mixture', 'moat', 'mobile', 'model', 'modify', 'mohawk', 'mom', 'moment',
  'monarch', 'mongrel', 'monitor', 'monkey', 'month', 'moon', 'moose', 'moral',
  'more', 'morning', 'mortar', 'mosaic', 'mosquito', 'mother', 'motion', 'motor',
  'mountain', 'mouse', 'move', 'movie', 'much', 'muffin', 'mullet', 'multiply',
  'muscle', 'museum', 'mushroom', 'music', 'muslin', 'mussel', 'must', 'mustang',
  'mutual', 'myrtle', 'myself', 'mystery', 'myth', 'naive', 'name', 'napkin',
  'narrow', 'narwhal', 'nation', 'nature', 'near', 'neck', 'nectar', 'need',
  'negative', 'neither', 'nephew', 'nest', 'nester', 'net', 'nettle', 'network',
  'neutral', 'never', 'news', 'newt', 'next', 'nice', 'nimble', 'noble',
  'noggin', 'noise', 'nomad', 'nominee', 'noodle', 'normal', 'north', 'nose',
  'notable', 'note', 'nothing', 'notice', 'novel', 'now', 'nuclear', 'number',
  'nurse', 'nut', 'nutmeg', 'oak', 'oakmoss', 'oasis', 'obey', 'object',
  'oblige', 'observe', 'obsidian', 'obtain', 'ocean', 'octave', 'october', 'odor',
  'off', 'offer', 'office', 'often', 'oil', 'okay', 'old', 'olive',
  'olympic', 'omit', 'once', 'onion', 'online', 'only', 'onyx', 'opal',
  'open', 'opera', 'opinion', 'oppose', 'option', 'orange', 'orbit', 'orchard',
  'orchid', 'order', 'ordinary', 'organ', 'orient', 'original', 'oriole', 'orphan',
  'osprey', 'ostrich', 'other', 'otter', 'outdoor', 'outer', 'outpost', 'output',
  'outside', 'oval', 'oven', 'over', 'own', 'owner', 'oxygen', 'oyster',
  'ozone', 'pact', 'paddle', 'page', 'pagoda', 'palace', 'palm', 'panda',
  'panel', 'panther', 'paper', 'parade', 'parent', 'park', 'parrot', 'party',
  'pass', 'patch', 'path', 'patient', 'patrol', 'pattern', 'pause', 'pave',
  'payment', 'peanut', 'peasant', 'pelican', 'pen', 'pencil', 'people', 'pepper',
  'perfect', 'permit', 'person', 'phone', 'photo', 'phrase', 'physical', 'piano',
  'picnic', 'picture', 'pigeon', 'pill', 'pilot', 'pink', 'pioneer', 'pipe',
  'pitch', 'pizza', 'place', 'planet', 'plastic', 'plate', 'play', 'please',
  'pledge', 'pluck', 'plug', 'poem', 'poet', 'point', 'polar', 'pole',
  'police', 'pond', 'pony', 'pool', 'popular', 'portion', 'position', 'possible',
  'post', 'potato', 'pottery', 'powder', 'power', 'practice', 'praise', 'predict',
  'prefer', 'prepare', 'present', 'pretty', 'prevent', 'price', 'pride', 'primary',
  'print', 'priority', 'private', 'prize', 'process', 'produce', 'profit', 'program',
  'project', 'promote', 'proof', 'property', 'prosper', 'protect', 'proud', 'provide',
  'public', 'pudding', 'pull', 'pulp', 'pulse', 'pumpkin', 'puppy', 'purchase',
  'purity', 'purpose', 'purse', 'push', 'put', 'puzzle', 'pyramid', 'quality',
  'quantum', 'quarter', 'question', 'quick', 'quiz', 'quote', 'rabbit', 'race',
  'rack', 'radar', 'radio', 'rail', 'rain', 'raise', 'rally', 'ramp',
  'ranch', 'random', 'range', 'rapid', 'rare', 'rate', 'rather', 'raven',
  'raw', 'razor', 'ready', 'real', 'reason', 'rebuild', 'recall', 'receive',
  'recipe', 'record', 'recycle', 'reduce', 'reflect', 'reform', 'refuse', 'region',
  'regular', 'relax', 'release', 'relief', 'rely', 'remain', 'remember', 'remove',
  'render', 'renew', 'rent', 'reopen', 'repair', 'repeat', 'replace', 'report',
  'require', 'rescue', 'resource', 'response', 'result', 'retire', 'retreat', 'return',
  'reunion', 'reveal', 'review', 'reward', 'rhythm', 'rib', 'ribbon', 'rice',
  'rich', 'ride', 'ridge', 'rifle', 'ring', 'ripple', 'risk', 'ritual',
  'rival', 'river', 'road', 'roast', 'robot', 'robust', 'rocket', 'romance',
  'roof', 'rookie', 'room', 'rose', 'rotate', 'round', 'route', 'royal',
  'rubber', 'rug', 'rule', 'run', 'runway', 'rural', 'saddle', 'sadness',
  'safe', 'salad', 'salmon', 'salon', 'salt', 'salute', 'same', 'sample',
  'sand', 'satisfy', 'satoshi', 'sauce', 'sausage', 'save', 'say', 'scale',
  'scan', 'school', 'science', 'scorpion', 'scout', 'screen', 'script', 'scrub',
  'search', 'season', 'seat', 'second', 'secret', 'section', 'security', 'seed',
  'seek', 'segment', 'select', 'sell', 'seminar', 'senior', 'sense', 'sentence',
  'service', 'session', 'settle', 'setup', 'seven', 'shadow', 'shallow', 'share',
  'shed', 'shell', 'sheriff', 'shield', 'shift', 'shine', 'shoe', 'shoot',
  'shop', 'short', 'shoulder', 'shove', 'shrimp', 'shuffle', 'shy', 'sibling',
  'sick', 'side', 'sight', 'sign', 'silent', 'silk', 'silly', 'silver',
  'similar', 'simple', 'since', 'sister', 'situate', 'six', 'size', 'skate',
  'sketch', 'ski', 'skill', 'skin', 'skirt', 'slab', 'slam', 'sleep',
  'slice', 'slide', 'slight', 'slim', 'small', 'smart', 'smile', 'smooth',
  'snack', 'snake', 'snow', 'soap', 'soccer', 'social', 'sock', 'soda',
  'soft', 'solar', 'soldier', 'solid', 'solution', 'solve', 'someone', 'song',
  'soon', 'sort', 'soul', 'sound', 'soup', 'source', 'south', 'space',
  'spare', 'spatial', 'speak', 'special', 'speed', 'spell', 'spend', 'sphere',
  'spice', 'spider', 'spike', 'spin', 'spirit', 'spoil', 'sponsor', 'spoon',
  'sport', 'spot', 'spray', 'spread', 'spring', 'spy', 'square', 'squirrel',
  'stable', 'stadium', 'staff', 'stage', 'stairs', 'stamp', 'stand', 'start',
  'state', 'stay', 'steak', 'stem', 'step', 'stereo', 'stick', 'still',
  'stock', 'stomach', 'stone', 'stool', 'story', 'stove', 'strategy', 'street',
  'strong', 'student', 'style', 'subject', 'submit', 'subway', 'success', 'such',
  'sudden', 'sugar', 'suggest', 'suit', 'summer', 'sunny', 'sunset', 'super',
  'supply', 'supreme', 'sure', 'surface', 'surge', 'surprise', 'surround', 'survey',
  'sustain', 'swap', 'swarm', 'sweet', 'swift', 'swim', 'swing', 'switch',
  'sword', 'symbol', 'syrup', 'system', 'table', 'tackle', 'tag', 'talent',
  'talk', 'tape', 'task', 'taste', 'taxi', 'teach', 'team', 'tell',
  'tennis', 'term', 'test', 'text', 'thank', 'theme', 'then', 'theory',
  'they', 'this', 'thought', 'thrive', 'throw', 'thumb', 'thunder', 'ticket',
  'tide', 'tiger', 'tilt', 'timber', 'time', 'tiny', 'tip', 'tired',
  'tissue', 'title', 'toast', 'today', 'toddler', 'together', 'toilet', 'token',
  'tomato', 'tomorrow', 'tone', 'tonight', 'tool', 'tooth', 'top', 'topic',
  'topple', 'torch', 'tortoise', 'toss', 'total', 'tourist', 'tower', 'town',
  'toy', 'track', 'trade', 'traffic', 'train', 'transfer', 'trap', 'travel',
  'tray', 'treat', 'trend', 'tribe', 'trick', 'trigger', 'trim', 'trip',
  'trophy', 'truck', 'true', 'trumpet', 'truth', 'try', 'tuition', 'tunnel',
  'turkey', 'turn', 'turtle', 'twelve', 'twenty', 'twice', 'twin', 'twist',
  'two', 'type', 'typical', 'umbrella', 'unable', 'unaware', 'uncle', 'uncover',
  'under', 'undo', 'unfair', 'unfold', 'uniform', 'unique', 'unit', 'universe',
  'unknown', 'unlock', 'until', 'unusual', 'update', 'upgrade', 'uphold', 'upon',
  'upper', 'upset', 'urban', 'urge', 'usage', 'use', 'used', 'useful',
  'useless', 'usual', 'utility', 'vague', 'valid', 'valley', 'valve', 'vapor',
  'various', 'vast', 'vehicle', 'velvet', 'vendor', 'venue', 'verb', 'verify',
  'version', 'very', 'vessel', 'veteran', 'viable', 'vibrant', 'vicious', 'victory',
  'video', 'village', 'vintage', 'violin', 'virtual', 'visa', 'visit', 'visual',
  'vital', 'vivid', 'vocal', 'voice', 'volcano', 'vote', 'voyage', 'wagon',
  'walk', 'wall', 'walnut', 'want', 'warm', 'warrior', 'wash', 'wasp',
  'water', 'wave', 'way', 'wealth', 'weasel', 'web', 'wedding', 'weekend',
  'welcome', 'west', 'wet', 'whale', 'what', 'wheat', 'wheel', 'when',
  'whip', 'whisper', 'wide', 'width', 'wife', 'wild', 'will', 'win',
  'window', 'wine', 'wing', 'wink', 'winner', 'winter', 'wire', 'wisdom',
  'wise', 'wish', 'witness', 'wolf', 'woman', 'wonder', 'wool', 'word',
  'work', 'world', 'worry', 'worth', 'wreck', 'wrestle', 'yard', 'year',
  'yellow', 'you', 'young', 'youth', 'zebra', 'zero', 'zone', 'zoo',

] as const

export const WORDLIST_SIZE = 2048

/** O(1) reverse lookup — built once at module load. */
const indexMap = new Map<string, number>()
for (let i = 0; i < WORDLIST.length; i++) {
  indexMap.set(WORDLIST[i], i)
}

/**
 * Return the word at the given index.
 *
 * @param index - Zero-based index into the wordlist (0-2047).
 * @returns The word at the specified index.
 * @throws {RangeError} If index is outside 0-2047.
 */
export function getWord(index: number): string {
  if (index < 0 || index >= WORDLIST_SIZE) {
    throw new RangeError(`Wordlist index out of range: ${index} (must be 0-${WORDLIST_SIZE - 1})`)
  }
  return WORDLIST[index]
}

/**
 * Return the index of a word, or -1 if it is not in the wordlist.
 *
 * @param word - The word to look up (must match exactly, case-sensitive).
 * @returns Zero-based index (0-2047) or -1 if not found.
 */
export function indexOf(word: string): number {
  return indexMap.get(word) ?? -1
}
